### ISSUE TITLE
bug: turan cse 7 is wrong

### ISSUE THREAD

**Issue by Satyvir-Singh** [lamBOOO/GeMotion.jl#1]
@lamBOOO please fix it

**Comment by lamBOOO** [comment]
Yes, I try to

**Comment by lamBOOO** [comment]
I have wuestion: Which Prandtl number is used?

**Comment by Satyvir-Singh** [comment]
use $\operatorname{Pr}=0.7$

**Comment by lamBOOO** [comment]
let's close this as it was just a test.
